[package]
name = "aoc"
version = "0.7.0"
authors = ["Mike Roberts"]
edition = "2021"
default-run = "aoc"
publish = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pico-args = "0.5.0"
regex = "1.7.0"
